FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run

RUN apt-get update && apt-get upgrade && apt-get install -yq \
    chromium-browser \
    lsb-core \
    alsa-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package.json package.json

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY . ./
COPY .asoundrc /root/.asoundrc

ENV UDEV=1

CMD ["npm", "start"]